// Generated by `wit-bindgen` 0.17.0. DO NOT EDIT!
#ifndef __BINDINGS_RUNTIME_H
#define __BINDINGS_RUNTIME_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  uint8_t*ptr;
  size_t len;
} runtime_string_t;

// Imported Functions from `runtime`
extern void runtime_print(runtime_string_t *msg);

// Exported Functions from `runtime`
void runtime_run(void);

// Helper Functions

// Transfers ownership of `s` into the string `ret`
void runtime_string_set(runtime_string_t *ret, char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void runtime_string_dup(runtime_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void runtime_string_free(runtime_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
